name: Actualizar Canales TVBox

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Clonar repositorio
        uses: actions/checkout@v4

      - name: 🐍 Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 📦 Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: 🎭 Instalar navegador Playwright
        run: playwright install chromium

      - name: 🚀 Ejecutar script de extracción
        run: python escanear_lista.py

      - name: 💾 Guardar y actualizar el archivo en GitHub
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add channels.js
          git commit -m "Auto-actualización de canales .m3u8 🤖" || echo "No hay cambios para guardar"
          git push
